# Generated by Django 2.2.5 on 2021-04-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210410_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('product_code', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
                ('features', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
