# Generated by Django 2.2.5 on 2021-04-10 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('user_name', models.CharField(max_length=250)),
                ('user_address', models.CharField(max_length=250)),
                ('user_phone', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('unit_price', models.CharField(max_length=250)),
                ('total_price', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
